### ISSUE TITLE
Error on build !

### ISSUE THREAD

**Issue by dorald** [mantissa/ofxVectorField#2]
Hi. I get this error 
![screen shot 2017-01-04 at 12 36 41](https://cloud.githubusercontent.com/assets/472782/21641237/d642d130-d27a-11e6-88d5-1472eb0db3a1.png)

OF : 0.9.8
Xcode : 8.2.1

**Comment by hurohukidaikon** [comment]
Hi. I fixed it like this.
`unsigned char * imagePixels = image.getPixels();`
to
`unsigned char * imagePixels = image.getPixels().getData();`

Good luck!

**Comment by dorald** [comment]
@hurohukidaikon thank you !
